name: Dirk Gadsden
url: https://dirk.to/blog
base_url: https://dirk.to
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: [footnotes]

keywords: "Dirk Gadsden, web development, programming, C, Ruby, JavaScript"
